[env]
EDITOR = "nvim"

[tools]
# keep-sorted start
"cargo:starship-jj" = "latest"
"go:github.com/google/keep-sorted" = "latest"
"npm:tdd-guard" = "latest"
"pipx:claude-conversation-extractor" = "latest"
act = "latest"
age = "latest"
ast-grep = "latest"
atuin = "latest"
bat = "latest"
bat-extras = "latest"
biome = "latest"
carapace = "latest"
chezmoi = "latest"
delta = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
ghcup = "latest"
glow = "latest"
go = "latest"
grex = "latest"
gum = "latest"
hyperfine = "latest"
jj = "latest"
jjui = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
lefthook = "latest"
mani = "latest"
maven = "latest"
mprocs = "latest"
neovim = "latest"
node = "latest"
pandoc = "latest"
pre-commit = "latest"
prettier = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
sd = "latest"
shellcheck = "latest"
sops = "latest"
starship = "latest"
taplo = "latest"
television = "latest"
tombi = "latest"
uv = "latest"
watchexec = "latest"
yamlfmt = "latest"
yazi = "latest"
yt-dlp = "latest"
zellij = "latest"
zoxide = "latest"
# keep-sorted end

[settings]
experimental = true
